services:
  sqldb:
    #image: now image created inside  dockerenv/Dockerfile
    build: 
      context: ./dockerenv
      #dockerfile: sqlSetup
    container_name: sqldb
    volumes:
      - data:/sql/data
    # environment:
    #   ACCEPT_EULA: "Y"
    #   SA_PASSWORD: "test123!!"
    ports:
      - 1433:1433
   
  # taskmanagement.api:
  #   image: ${DOCKER_REGISTRY-}taskmanagementapi
  #   build:
  #     context: .
  #     dockerfile: TaskManagement.API/Dockerfile
  #   depends_on:
  #     - sqldb

volumes:
  data: