services:
  sqldb:
  #image: now image created inside  dockerenv/Dockerfile
    build: 
      context: ./dockerenv    
    container_name: sqldb
    volumes:
      - data:/sql/data
    # environment:
    #   ACCEPT_EULA: "Y"
    #   SA_PASSWORD: "test123!!"
    ports:
      - 1433:1433
  

  # taskmanagement.api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #   ports:
  #     - "8080"
  #     - "8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
volumes:
  data: