services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqldb
    volumes:
      - data:/sql/data
    # environment:
    #   ACCEPT_EULA: "Y"
    #   SA_PASSWORD: "test123!!"
    ports:
      - 1433:1433
    env_file:
      - ./dockerenv/sql.env
   
  # taskmanagement.api:
  #   image: ${DOCKER_REGISTRY-}taskmanagementapi
  #   build:
  #     context: .
  #     dockerfile: TaskManagement.API/Dockerfile
  #   depends_on:
  #     - sqldb

volumes:
  data: